export { default as Home } from '../pages/home/Home'
export { default as Chat } from './oop/Chat'
export { default as Navigator } from './common/Navigator'
export { default as Clock } from '../components/oop/Clock'
export { default as Counter } from '../components/oop/Counter'
export { default as Hello } from '../components/oop/Hello'
export { default as Cat } from '../components/oop/Cat'